# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/julio/tools/migortho

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/julio/tools/migortho

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/julio/tools/migortho/CMakeFiles /home/julio/tools/migortho/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/julio/tools/migortho/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fiction

# Build rule for target.
fiction: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fiction
.PHONY : fiction

# fast build rule for target.
fiction/fast:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/build
.PHONY : fiction/fast

#=============================================================================
# Target rules for targets named z3

# Build rule for target.
z3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 z3
.PHONY : z3

# fast build rule for target.
z3/fast:
	$(MAKE) -f CMakeFiles/z3.dir/build.make CMakeFiles/z3.dir/build
.PHONY : z3/fast

#=============================================================================
# Target rules for targets named pretty_print

# Build rule for target.
pretty_print: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pretty_print
.PHONY : pretty_print

# fast build rule for target.
pretty_print/fast:
	$(MAKE) -f libs/lorina/examples/CMakeFiles/pretty_print.dir/build.make libs/lorina/examples/CMakeFiles/pretty_print.dir/build
.PHONY : pretty_print/fast

#=============================================================================
# Target rules for targets named libabcsat

# Build rule for target.
libabcsat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libabcsat
.PHONY : libabcsat

# fast build rule for target.
libabcsat/fast:
	$(MAKE) -f lib/abcsat/CMakeFiles/libabcsat.dir/build.make lib/abcsat/CMakeFiles/libabcsat.dir/build
.PHONY : libabcsat/fast

src/algo/exact_pr.o: src/algo/exact_pr.cpp.o

.PHONY : src/algo/exact_pr.o

# target to build an object file
src/algo/exact_pr.cpp.o:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/algo/exact_pr.cpp.o
.PHONY : src/algo/exact_pr.cpp.o

src/algo/exact_pr.i: src/algo/exact_pr.cpp.i

.PHONY : src/algo/exact_pr.i

# target to preprocess a source file
src/algo/exact_pr.cpp.i:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/algo/exact_pr.cpp.i
.PHONY : src/algo/exact_pr.cpp.i

src/algo/exact_pr.s: src/algo/exact_pr.cpp.s

.PHONY : src/algo/exact_pr.s

# target to generate assembly for a file
src/algo/exact_pr.cpp.s:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/algo/exact_pr.cpp.s
.PHONY : src/algo/exact_pr.cpp.s

src/algo/migorthogonal_pr.o: src/algo/migorthogonal_pr.cpp.o

.PHONY : src/algo/migorthogonal_pr.o

# target to build an object file
src/algo/migorthogonal_pr.cpp.o:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/algo/migorthogonal_pr.cpp.o
.PHONY : src/algo/migorthogonal_pr.cpp.o

src/algo/migorthogonal_pr.i: src/algo/migorthogonal_pr.cpp.i

.PHONY : src/algo/migorthogonal_pr.i

# target to preprocess a source file
src/algo/migorthogonal_pr.cpp.i:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/algo/migorthogonal_pr.cpp.i
.PHONY : src/algo/migorthogonal_pr.cpp.i

src/algo/migorthogonal_pr.s: src/algo/migorthogonal_pr.cpp.s

.PHONY : src/algo/migorthogonal_pr.s

# target to generate assembly for a file
src/algo/migorthogonal_pr.cpp.s:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/algo/migorthogonal_pr.cpp.s
.PHONY : src/algo/migorthogonal_pr.cpp.s

src/algo/orthogonal_pr.o: src/algo/orthogonal_pr.cpp.o

.PHONY : src/algo/orthogonal_pr.o

# target to build an object file
src/algo/orthogonal_pr.cpp.o:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/algo/orthogonal_pr.cpp.o
.PHONY : src/algo/orthogonal_pr.cpp.o

src/algo/orthogonal_pr.i: src/algo/orthogonal_pr.cpp.i

.PHONY : src/algo/orthogonal_pr.i

# target to preprocess a source file
src/algo/orthogonal_pr.cpp.i:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/algo/orthogonal_pr.cpp.i
.PHONY : src/algo/orthogonal_pr.cpp.i

src/algo/orthogonal_pr.s: src/algo/orthogonal_pr.cpp.s

.PHONY : src/algo/orthogonal_pr.s

# target to generate assembly for a file
src/algo/orthogonal_pr.cpp.s:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/algo/orthogonal_pr.cpp.s
.PHONY : src/algo/orthogonal_pr.cpp.s

src/fiction.o: src/fiction.cpp.o

.PHONY : src/fiction.o

# target to build an object file
src/fiction.cpp.o:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/fiction.cpp.o
.PHONY : src/fiction.cpp.o

src/fiction.i: src/fiction.cpp.i

.PHONY : src/fiction.i

# target to preprocess a source file
src/fiction.cpp.i:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/fiction.cpp.i
.PHONY : src/fiction.cpp.i

src/fiction.s: src/fiction.cpp.s

.PHONY : src/fiction.s

# target to generate assembly for a file
src/fiction.cpp.s:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/fiction.cpp.s
.PHONY : src/fiction.cpp.s

src/io/qca_writer.o: src/io/qca_writer.cpp.o

.PHONY : src/io/qca_writer.o

# target to build an object file
src/io/qca_writer.cpp.o:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/io/qca_writer.cpp.o
.PHONY : src/io/qca_writer.cpp.o

src/io/qca_writer.i: src/io/qca_writer.cpp.i

.PHONY : src/io/qca_writer.i

# target to preprocess a source file
src/io/qca_writer.cpp.i:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/io/qca_writer.cpp.i
.PHONY : src/io/qca_writer.cpp.i

src/io/qca_writer.s: src/io/qca_writer.cpp.s

.PHONY : src/io/qca_writer.s

# target to generate assembly for a file
src/io/qca_writer.cpp.s:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/io/qca_writer.cpp.s
.PHONY : src/io/qca_writer.cpp.s

src/io/svg_writer.o: src/io/svg_writer.cpp.o

.PHONY : src/io/svg_writer.o

# target to build an object file
src/io/svg_writer.cpp.o:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/io/svg_writer.cpp.o
.PHONY : src/io/svg_writer.cpp.o

src/io/svg_writer.i: src/io/svg_writer.cpp.i

.PHONY : src/io/svg_writer.i

# target to preprocess a source file
src/io/svg_writer.cpp.i:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/io/svg_writer.cpp.i
.PHONY : src/io/svg_writer.cpp.i

src/io/svg_writer.s: src/io/svg_writer.cpp.s

.PHONY : src/io/svg_writer.s

# target to generate assembly for a file
src/io/svg_writer.cpp.s:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/io/svg_writer.cpp.s
.PHONY : src/io/svg_writer.cpp.s

src/tech/fcn_cell_layout.o: src/tech/fcn_cell_layout.cpp.o

.PHONY : src/tech/fcn_cell_layout.o

# target to build an object file
src/tech/fcn_cell_layout.cpp.o:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/tech/fcn_cell_layout.cpp.o
.PHONY : src/tech/fcn_cell_layout.cpp.o

src/tech/fcn_cell_layout.i: src/tech/fcn_cell_layout.cpp.i

.PHONY : src/tech/fcn_cell_layout.i

# target to preprocess a source file
src/tech/fcn_cell_layout.cpp.i:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/tech/fcn_cell_layout.cpp.i
.PHONY : src/tech/fcn_cell_layout.cpp.i

src/tech/fcn_cell_layout.s: src/tech/fcn_cell_layout.cpp.s

.PHONY : src/tech/fcn_cell_layout.s

# target to generate assembly for a file
src/tech/fcn_cell_layout.cpp.s:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/tech/fcn_cell_layout.cpp.s
.PHONY : src/tech/fcn_cell_layout.cpp.s

src/tech/fcn_gate_library.o: src/tech/fcn_gate_library.cpp.o

.PHONY : src/tech/fcn_gate_library.o

# target to build an object file
src/tech/fcn_gate_library.cpp.o:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/tech/fcn_gate_library.cpp.o
.PHONY : src/tech/fcn_gate_library.cpp.o

src/tech/fcn_gate_library.i: src/tech/fcn_gate_library.cpp.i

.PHONY : src/tech/fcn_gate_library.i

# target to preprocess a source file
src/tech/fcn_gate_library.cpp.i:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/tech/fcn_gate_library.cpp.i
.PHONY : src/tech/fcn_gate_library.cpp.i

src/tech/fcn_gate_library.s: src/tech/fcn_gate_library.cpp.s

.PHONY : src/tech/fcn_gate_library.s

# target to generate assembly for a file
src/tech/fcn_gate_library.cpp.s:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/tech/fcn_gate_library.cpp.s
.PHONY : src/tech/fcn_gate_library.cpp.s

src/tech/fcn_technology.o: src/tech/fcn_technology.cpp.o

.PHONY : src/tech/fcn_technology.o

# target to build an object file
src/tech/fcn_technology.cpp.o:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/tech/fcn_technology.cpp.o
.PHONY : src/tech/fcn_technology.cpp.o

src/tech/fcn_technology.i: src/tech/fcn_technology.cpp.i

.PHONY : src/tech/fcn_technology.i

# target to preprocess a source file
src/tech/fcn_technology.cpp.i:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/tech/fcn_technology.cpp.i
.PHONY : src/tech/fcn_technology.cpp.i

src/tech/fcn_technology.s: src/tech/fcn_technology.cpp.s

.PHONY : src/tech/fcn_technology.s

# target to generate assembly for a file
src/tech/fcn_technology.cpp.s:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/tech/fcn_technology.cpp.s
.PHONY : src/tech/fcn_technology.cpp.s

src/tech/port_router.o: src/tech/port_router.cpp.o

.PHONY : src/tech/port_router.o

# target to build an object file
src/tech/port_router.cpp.o:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/tech/port_router.cpp.o
.PHONY : src/tech/port_router.cpp.o

src/tech/port_router.i: src/tech/port_router.cpp.i

.PHONY : src/tech/port_router.i

# target to preprocess a source file
src/tech/port_router.cpp.i:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/tech/port_router.cpp.i
.PHONY : src/tech/port_router.cpp.i

src/tech/port_router.s: src/tech/port_router.cpp.s

.PHONY : src/tech/port_router.s

# target to generate assembly for a file
src/tech/port_router.cpp.s:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/tech/port_router.cpp.s
.PHONY : src/tech/port_router.cpp.s

src/tech/qca_one_library.o: src/tech/qca_one_library.cpp.o

.PHONY : src/tech/qca_one_library.o

# target to build an object file
src/tech/qca_one_library.cpp.o:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/tech/qca_one_library.cpp.o
.PHONY : src/tech/qca_one_library.cpp.o

src/tech/qca_one_library.i: src/tech/qca_one_library.cpp.i

.PHONY : src/tech/qca_one_library.i

# target to preprocess a source file
src/tech/qca_one_library.cpp.i:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/tech/qca_one_library.cpp.i
.PHONY : src/tech/qca_one_library.cpp.i

src/tech/qca_one_library.s: src/tech/qca_one_library.cpp.s

.PHONY : src/tech/qca_one_library.s

# target to generate assembly for a file
src/tech/qca_one_library.cpp.s:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/tech/qca_one_library.cpp.s
.PHONY : src/tech/qca_one_library.cpp.s

src/topo/directions.o: src/topo/directions.cpp.o

.PHONY : src/topo/directions.o

# target to build an object file
src/topo/directions.cpp.o:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/topo/directions.cpp.o
.PHONY : src/topo/directions.cpp.o

src/topo/directions.i: src/topo/directions.cpp.i

.PHONY : src/topo/directions.i

# target to preprocess a source file
src/topo/directions.cpp.i:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/topo/directions.cpp.i
.PHONY : src/topo/directions.cpp.i

src/topo/directions.s: src/topo/directions.cpp.s

.PHONY : src/topo/directions.s

# target to generate assembly for a file
src/topo/directions.cpp.s:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/topo/directions.cpp.s
.PHONY : src/topo/directions.cpp.s

src/topo/fcn_clocking_scheme.o: src/topo/fcn_clocking_scheme.cpp.o

.PHONY : src/topo/fcn_clocking_scheme.o

# target to build an object file
src/topo/fcn_clocking_scheme.cpp.o:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/topo/fcn_clocking_scheme.cpp.o
.PHONY : src/topo/fcn_clocking_scheme.cpp.o

src/topo/fcn_clocking_scheme.i: src/topo/fcn_clocking_scheme.cpp.i

.PHONY : src/topo/fcn_clocking_scheme.i

# target to preprocess a source file
src/topo/fcn_clocking_scheme.cpp.i:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/topo/fcn_clocking_scheme.cpp.i
.PHONY : src/topo/fcn_clocking_scheme.cpp.i

src/topo/fcn_clocking_scheme.s: src/topo/fcn_clocking_scheme.cpp.s

.PHONY : src/topo/fcn_clocking_scheme.s

# target to generate assembly for a file
src/topo/fcn_clocking_scheme.cpp.s:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/topo/fcn_clocking_scheme.cpp.s
.PHONY : src/topo/fcn_clocking_scheme.cpp.s

src/topo/fcn_gate_layout.o: src/topo/fcn_gate_layout.cpp.o

.PHONY : src/topo/fcn_gate_layout.o

# target to build an object file
src/topo/fcn_gate_layout.cpp.o:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/topo/fcn_gate_layout.cpp.o
.PHONY : src/topo/fcn_gate_layout.cpp.o

src/topo/fcn_gate_layout.i: src/topo/fcn_gate_layout.cpp.i

.PHONY : src/topo/fcn_gate_layout.i

# target to preprocess a source file
src/topo/fcn_gate_layout.cpp.i:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/topo/fcn_gate_layout.cpp.i
.PHONY : src/topo/fcn_gate_layout.cpp.i

src/topo/fcn_gate_layout.s: src/topo/fcn_gate_layout.cpp.s

.PHONY : src/topo/fcn_gate_layout.s

# target to generate assembly for a file
src/topo/fcn_gate_layout.cpp.s:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/topo/fcn_gate_layout.cpp.s
.PHONY : src/topo/fcn_gate_layout.cpp.s

src/topo/fcn_layout.o: src/topo/fcn_layout.cpp.o

.PHONY : src/topo/fcn_layout.o

# target to build an object file
src/topo/fcn_layout.cpp.o:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/topo/fcn_layout.cpp.o
.PHONY : src/topo/fcn_layout.cpp.o

src/topo/fcn_layout.i: src/topo/fcn_layout.cpp.i

.PHONY : src/topo/fcn_layout.i

# target to preprocess a source file
src/topo/fcn_layout.cpp.i:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/topo/fcn_layout.cpp.i
.PHONY : src/topo/fcn_layout.cpp.i

src/topo/fcn_layout.s: src/topo/fcn_layout.cpp.s

.PHONY : src/topo/fcn_layout.s

# target to generate assembly for a file
src/topo/fcn_layout.cpp.s:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/topo/fcn_layout.cpp.s
.PHONY : src/topo/fcn_layout.cpp.s

src/topo/logic_network.o: src/topo/logic_network.cpp.o

.PHONY : src/topo/logic_network.o

# target to build an object file
src/topo/logic_network.cpp.o:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/topo/logic_network.cpp.o
.PHONY : src/topo/logic_network.cpp.o

src/topo/logic_network.i: src/topo/logic_network.cpp.i

.PHONY : src/topo/logic_network.i

# target to preprocess a source file
src/topo/logic_network.cpp.i:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/topo/logic_network.cpp.i
.PHONY : src/topo/logic_network.cpp.i

src/topo/logic_network.s: src/topo/logic_network.cpp.s

.PHONY : src/topo/logic_network.s

# target to generate assembly for a file
src/topo/logic_network.cpp.s:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/topo/logic_network.cpp.s
.PHONY : src/topo/logic_network.cpp.s

src/topo/operations.o: src/topo/operations.cpp.o

.PHONY : src/topo/operations.o

# target to build an object file
src/topo/operations.cpp.o:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/topo/operations.cpp.o
.PHONY : src/topo/operations.cpp.o

src/topo/operations.i: src/topo/operations.cpp.i

.PHONY : src/topo/operations.i

# target to preprocess a source file
src/topo/operations.cpp.i:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/topo/operations.cpp.i
.PHONY : src/topo/operations.cpp.i

src/topo/operations.s: src/topo/operations.cpp.s

.PHONY : src/topo/operations.s

# target to generate assembly for a file
src/topo/operations.cpp.s:
	$(MAKE) -f CMakeFiles/fiction.dir/build.make CMakeFiles/fiction.dir/src/topo/operations.cpp.s
.PHONY : src/topo/operations.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... fiction"
	@echo "... edit_cache"
	@echo "... z3"
	@echo "... pretty_print"
	@echo "... libabcsat"
	@echo "... src/algo/exact_pr.o"
	@echo "... src/algo/exact_pr.i"
	@echo "... src/algo/exact_pr.s"
	@echo "... src/algo/migorthogonal_pr.o"
	@echo "... src/algo/migorthogonal_pr.i"
	@echo "... src/algo/migorthogonal_pr.s"
	@echo "... src/algo/orthogonal_pr.o"
	@echo "... src/algo/orthogonal_pr.i"
	@echo "... src/algo/orthogonal_pr.s"
	@echo "... src/fiction.o"
	@echo "... src/fiction.i"
	@echo "... src/fiction.s"
	@echo "... src/io/qca_writer.o"
	@echo "... src/io/qca_writer.i"
	@echo "... src/io/qca_writer.s"
	@echo "... src/io/svg_writer.o"
	@echo "... src/io/svg_writer.i"
	@echo "... src/io/svg_writer.s"
	@echo "... src/tech/fcn_cell_layout.o"
	@echo "... src/tech/fcn_cell_layout.i"
	@echo "... src/tech/fcn_cell_layout.s"
	@echo "... src/tech/fcn_gate_library.o"
	@echo "... src/tech/fcn_gate_library.i"
	@echo "... src/tech/fcn_gate_library.s"
	@echo "... src/tech/fcn_technology.o"
	@echo "... src/tech/fcn_technology.i"
	@echo "... src/tech/fcn_technology.s"
	@echo "... src/tech/port_router.o"
	@echo "... src/tech/port_router.i"
	@echo "... src/tech/port_router.s"
	@echo "... src/tech/qca_one_library.o"
	@echo "... src/tech/qca_one_library.i"
	@echo "... src/tech/qca_one_library.s"
	@echo "... src/topo/directions.o"
	@echo "... src/topo/directions.i"
	@echo "... src/topo/directions.s"
	@echo "... src/topo/fcn_clocking_scheme.o"
	@echo "... src/topo/fcn_clocking_scheme.i"
	@echo "... src/topo/fcn_clocking_scheme.s"
	@echo "... src/topo/fcn_gate_layout.o"
	@echo "... src/topo/fcn_gate_layout.i"
	@echo "... src/topo/fcn_gate_layout.s"
	@echo "... src/topo/fcn_layout.o"
	@echo "... src/topo/fcn_layout.i"
	@echo "... src/topo/fcn_layout.s"
	@echo "... src/topo/logic_network.o"
	@echo "... src/topo/logic_network.i"
	@echo "... src/topo/logic_network.s"
	@echo "... src/topo/operations.o"
	@echo "... src/topo/operations.i"
	@echo "... src/topo/operations.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

