set key below;
set grid ;
set boxwidth 1 ;
set style fill solid 0.5 ;
set datafile sep ';'
set term png ;
set title 'Avalição Scripts Mockturtle';
set output '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.png' ;
set ylabel 'Gates'; set xlabel 'Scripts'; set noxtics;
plot '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (2): 2 with boxplot lw 2 title 'Original' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (4): 4 with boxplot lw 2 title '2migRefac' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (8): 8 with boxplot lw 2 title '3migAlg' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (12): 12 with boxplot lw 2 title 'mix2k5' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (16): 16 with boxplot lw 2 title 'mix2k3' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (20): 20 with boxplot lw 2 title '3migCutRewritek4' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (24): 24 with boxplot lw 2 title '3migCutRewritek3' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (28): 28 with boxplot lw 2 title 'mix1k3' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (32): 32 with boxplot lw 2 title '2migCutRewritek4' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (36): 36 with boxplot lw 2 title 'mix4k5' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (40): 40 with boxplot lw 2 title '3migRefac' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (44): 44 with boxplot lw 2 title 'mix3k5' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (48): 48 with boxplot lw 2 title '2migAlg' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (52): 52 with boxplot lw 2 title 'migRefac' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (56): 56 with boxplot lw 2 title 'mix4k3' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (60): 60 with boxplot lw 2 title 'mix1k4' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (64): 64 with boxplot lw 2 title 'migAlg' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (68): 68 with boxplot lw 2 title 'mix3k4' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (72): 72 with boxplot lw 2 title 'mix4k4' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (76): 76 with boxplot lw 2 title 'mix2k4' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (80): 80 with boxplot lw 2 title '2migCutRewritek3' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (84): 84 with boxplot lw 2 title 'mix1k5' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (88): 88 with boxplot lw 2 title '3migResub' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (92): 92 with boxplot lw 2 title 'migCutrewritek4' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (96): 96 with boxplot lw 2 title 'mix3k3' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (100):100 with boxplot lw 2 title 'migResub' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (104):104 with boxplot lw 2 title 'migCutRewritek3' , '../OUT-benchmarks/ISCAS85_EVALUATION_GENERAL.xls' using (108):108 with boxplot lw 2 title '2migResub' 
